import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "@/context/AuthContext"; // ✅ add

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* ✅ wrap whole app so useAuth works everywhere */}
        <AuthProvider>
          {children}
        </AuthProvider>

        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}